version: "7.2.3"

services:

  #mkt01:
  #  image: cnsoluciones/mikrotik:latest
  routeros:
    image: nanopi/mikrotik:latest
    container_name: routeros
    restart: always
    ports:
      - "121:21"
      - "122:22"
      - "123:23"
      - "150:50"
      - "151:51"
      - "180:80"
      - "1443:443"
      - "500:500"
      - "11194:1194"
      - "1701:1701"
      - "1723:1723"
      - "4500:4500"
      - "15900:5900"
      - "18080:8080"
      - "18291:8291"
      - "18728:8728"
      - "18729:8729"
    environment:
      - "VNCPASSWORD=false"
    network_mode: bridge
    privileged: true


  winbox:
    image: nanopi/novnc-winbox:latest
    container_name: winbox
    hostname: winbox
    restart: always
    #volumes:
    #  - ./user-data/.wine:/home/alpine/.wine
    links:
      - "routeros"
    ports:
      - "5901:5900"
      - "18081:8080"
    network_mode: bridge
